---
- name: "clone zprezto project"
  git:
    repo: https://github.com/pavel-v-chernykh/prezto.git
    dest: '{{ dotfiles_zprezto_project_dir }}'
    depth: 1

- name: "change shell"
  command: "chsh -s /bin/zsh {{ ansible_env.USER}}"
  sudo: yes

- name: "replace gitconfig"
  template:
    src: "gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"

- name: "replace hgrc"
  template:
    src: "hgrc"
    dest: "{{ ansible_env.HOME }}/.hgrc"

- name: "replace tmux.conf"
  template:
    src: "tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"

- name: "replace zlogin"
  template:
    src: "zlogin"
    dest: "{{ ansible_env.HOME }}/.zlogin"

- name: "replace zlogout"
  template:
    src: "zlogout"
    dest: "{{ ansible_env.HOME }}/.zlogout"

- name: "replace zpreztorc"
  template:
    src: "zpreztorc"
    dest: "{{ ansible_env.HOME }}/.zpreztorc"

- name: "replace zprofile"
  template:
    src: "zprofile"
    dest: "{{ ansible_env.HOME }}/.zprofile"

- name: "replace zshenv"
  template:
    src: "zshenv"
    dest: "{{ ansible_env.HOME }}/.zshenv"

- name: "replace zshrc"
  template:
    src: "zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
