---
- name: "clone zprezto project"
  git: repo=https://github.com/pavel-v-chernykh/prezto.git dest={{ zprezto_project_dir }}

- name: "link zprezto"
  shell: "ln -nsf {{ zprezto_project_dir }} {{ ansible_env.HOME }}/.zprezto"

- name: "change shell"
  shell: "chsh -s {{ user_shell }} `whoami`"
  sudo: yes

- name: "replace gitconfig"
  template:
    src: "gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"

- name: "replace hgrc"
  template:
    src: "hgrc"
    dest: "{{ ansible_env.HOME }}/.hgrc"

- name: "replace tmux.conf"
  template:
    src: "tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"

- name: "replace vimrc"
  template:
    src: "vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: "replace zpreztorc"
  template:
    src: "zpreztorc"
    dest: "{{ ansible_env.HOME }}/.zpreztorc"

- name: "replace zshenv"
  template:
    src: "zshenv"
    dest: "{{ ansible_env.HOME }}/.zshenv"

- name: "replace zshrc"
  template:
    src: "zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
