---
- name: Make sure the packages are installed (Debian)
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: dotfiles_essential_packages
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Make sure the packages are installed (Darwin)
  homebrew:
    pkg: "{{ item }}"
    state: present
    update_homebrew: yes
  with_items: dotfiles_essential_packages
  when: ansible_os_family == "Darwin"
