---
- name: Read the family variables
  include_vars: "{{ ansible_os_family }}.yaml"

- name: Make sure the packages are installed (Debian)
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: essential_packages
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Make sure the packages are installed (Darwin)
  homebrew:
    pkg: "{{ item }}"
    state: present
  with_items: essential_packages
  when: ansible_os_family == "Darwin"
